name = "moenaigomi"
compatibility_date = "2026-07-09"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "moenaigomi-db"
database_id = "ac916b62-a967-40a4-8e83-0e33fd10db5f"
