ALTER TABLE items ADD COLUMN description TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN additionalImages TEXT NOT NULL DEFAULT '';
ALTER TABLE items ADD COLUMN additionalInfo TEXT NOT NULL DEFAULT '';
